### ISSUE TITLE
org.freedesktop.Notifications systemd service does not use any configuration file

### ISSUE THREAD

**Issue by danmilon** [mk-fg/notification-thing#6]
Hello,

I noticed that the supplied notifications service file does not use any configuration file, like [the other one does](https://github.com/mk-fg/notification-thing/blob/master/notification-thing.service#L9-L10).

Is that intended? If not, can we have it use a default configuration file if available?

**Comment by mk-fg** [comment]
Hi,

Was thinking of these files examples rather than something a package would install as-is, so didn't go for consistency, and systemd one is just the one I use in my desktop setup.

YAML dependency is optional, as it's only used to parse config or --net-settings, so didn't want to use default config path due to that, in addition to not wanting to decide on any hardcoded name for it.

So if you're installing dbus/systemd configs in the distro, maybe ship them with distro-specific defaults in the package, or use static files in case of an individual setup, instead of pulling them from this repository.
They are unlikely to change anyway, as that'd mean dropping support for some options, and in an unlikely case when they do, should be obvious from the very first run (as app would reject them).

Guess I'll also add a comment to this effect on top of these files.

**Comment by mk-fg** [comment]
Also, wow, you seem to be not just only other user of this app, but a somewhat long-term one! :)

**Comment by danmilon** [comment]
Alright, makes sense. Does it gracefully handle the yaml dependency missing? For example, if you do:
```
notification-thing --config ~/.notification.yaml --conf-missing-ok
```
when the yaml python package is not installed, and the configuration is missing, does it still run with defaults?

In that case, we could put that in the systemd service file and still have yaml being an optional dep.

I agree the path and file name mentioned in the docs (`~/.notification.yaml`) are not ideal. It should live in  `$XDG_CONFIG_HOME` in its own folder. e.g. `.config/notification-thing/configuration.yaml`. Do you not want to set a default at all for `--conf`, or you're not decided what to set it to yet? 

I dont remember where I stumbled upon this, but TBH it's a pretty neat notification daemon and really gets the job done! Also I just found out I'm the maintainer for the [archlinux user package](https://aur.archlinux.org/packages/notification-thing-git)! I had forgotten that :)

thanks for everything!

**Comment by mk-fg** [comment]
> Alright, makes sense. Does it gracefully handle the yaml dependency missing?

No, I don't think there's "graceful" way to do it if you say "I want my config file" - seems wrong to silently ignore it if option is explicitly specified and dependency is missing.

> In that case, we could put that in the systemd service file and still have yaml being an optional dep.

I think in a distro package, you'd use --conf + --conf-missing-ok and just hard-code yaml as being dependency, no need to bother user with options for a few .py files which OS can install for them automatically.

**Comment by danmilon** [comment]
Sounds good, thanks :)

**Comment by mk-fg** [comment]
Thanks for maintaining that.

I use arch too, but have (apparently outdated) pkgbuild in a local repo:
https://github.com/mk-fg/archlinux-pkgbuilds/blob/master/notification-thing-git/PKGBUILD
